DATA_HERE	SEGMENT
		MULTIPLICANDO DW 204AH
		MULTIPLICADOR DW 382AH
		PRODUTO DW 2 DUP(0)
DATA_HERE 	ENDS
CODE_HERE	SEGMENT
		ASSUME CS:CODE_HERE, DS:DATA_HERE
		MOV AX, DATA_HERE
		MOV DS, AX
		MOV AX, MULTIPLICANDO
		MUL MULTIPLICADOR
		MOV PRODUTO, AX
		MOV PRODUTO+2, DX
		MOV AH, 4CH
		INT 21H
CODE_HERE 	ENDS
		END
